### ISSUE TITLE
# frozen_string_literal: true hatası

### ISSUE THREAD

**Issue by omerozturk0** [sbagdat/turkish_support#11]
Sayfanın başına `# frozen_string_literal: true` magic comment ekledikten sonra upcase ve downcase string fonksiyonlarında **can't define singleton** gibi bir hata alıyorum.

**Comment by sbagdat** [comment]
Gem'in kullandığı bazı stringler için `# frozen_string_literal: true` yorumu kullanılmaması gerekiyor. Bütün stringleri freeze ettiğiniz için böyle bir hata alıyorsunuz. Gem kaynaklı bir hata değil yani. Bildiriminiz için teşekkürler.

**Comment by omerozturk0** [comment]
Gem kaynaklı sorun değil evet. Fakat daha sonra aynı sorun ile karşılaşacak arkadaşlar için çözümü şu şekilde sağlanabilir.

`a = ['deneme', 'deneme1', 'deneme2']` dizisini ele alalım ve dizi elemanlarının hepsini büyük harfe çevirmek istediğimizi varsayalım.

Sayfa başına `# frozen_string_literal: true` eklendiği taktirde issue'de belirttiğim hatayı almak istemiyorsanız.

`a.flat_map(&:dup).flat_map(&:upcase)` şeklinde kullanabilirsiniz.
