### ISSUE TITLE
Stack level too deep error for string_methods

### ISSUE THREAD

**Issue by enderahmetyurt** [sbagdat/turkish_support#13]
I am trying to comparison strings with usign Ruby upcase method. For example;

```ruby
banks.select { |b| b["banka"]["bAd"] == bank_name.upcase }
```
Here when I try to run rspec tests I faced `SystemStackError: stack level too deep` error. It occurs on 

`../ruby-2.6.2/gems/turkish_support-1.1.3/lib/turkish_support/string_methods.rb:18` 

Could you help me? 

Cheers.

**Comment by computalya** [comment]
I've got same error message with ruby 2.6.3 and rails 6.0.0-rc2

**Comment by enderahmetyurt** [comment]
I talked to @sbagdat he told me he was working on that issue.

**Comment by enderahmetyurt** [comment]
i guess it's a ruby 2.6.x problem. I don't face any errors with ruby 2.5.x

**Comment by rokumatsumoto** [comment]
https://github.com/ruby/ruby/search?p=1&q=%3Aturkic&unscoped_q=%3Aturkic

**Comment by sbagdat** [comment]
> https://github.com/ruby/ruby/search?p=1&q=%3Aturkic&unscoped_q=%3Aturkic

?

**Comment by rokumatsumoto** [comment]
> > [ruby/ruby/search?p=1&q=%3Aturkic&unscoped_q=%3Aturkic](https://github.com/ruby/ruby/search?p=1&q=%3Aturkic&unscoped_q=%3Aturkic)
> 
> ?

With `Ruby 2.4.6`, `downcase` and `upcase` methods support the Turkish language. I haven't looked at other `String` methods yet.

https://apidock.com/ruby/v2_4_6/String/downcase
https://apidock.com/ruby/v2_4_6/String/upcase

```ruby
[1] pry(main)> 'içel'.upcase(:turkic)
=> "İÇEL"
```
