### ISSUE TITLE
Ruby 2.2.2'de çalışmıyor.

### ISSUE THREAD

**Issue by lacriment** [sbagdat/turkish_support#4]
Linux Yaz Kampında sınıf olarak Ruby 2.2.2 pry'da çalıştıramadık.

**Comment by lacriment** [comment]
sorun irb ve pry için geçerli, .rb dosyasında sorun yok.

**Comment by sbagdat** [comment]
Ruby 2.1.0'den itibaren refinements kullanımı terminalde çalışmıyor malesef. Paket ile ilgili bir sorun değil yani...
