### ISSUE TITLE
comparison of Array with Array failed (ArgumentError)

### ISSUE THREAD

**Issue by computalya** [sbagdat/turkish_support#7]
önce hata çıktısı

`.rvm/gems/ruby-2.3.3@rails5_1_1/gems/turkish_support-1.0.3/lib/turkish_support/array_methods.rb:4:in `sort_by': comparison of Array with Array failed (ArgumentError)`

`.rvm/gems/ruby-2.3.3@rails5_1_1/gems/turkish_support-1.0.3/lib/turkish_support/array_methods.rb:4:in `sort'
	from ./sort.rb:13:in `<main>'`

bu hatayı içinde türkçe karakter olmayan dizinlerde de alıyorum

```ruby
# şu sorunsuz çalışıyor
['isim soyisim', 'isim soyisim'].sort

# şu ise çalışmıyor
['isim soyisim', 'isim1 soyisim'].sort

# aynı şekilde bu da çalışmıyor
['isim1 soyisim', 'isim soyisim'].sort
```

sorun sadece boşluk olmasında da değil

```ruby
# bu çalışıyor
['isim1soyisim', 'isim2soyisim'].sort

# bunlar ise çalışmıyor
['isim1soyisim', 'isim21soyisim'].sort
['1soyisim', '12soyisim'].sort
['a', '3s'].sort
['1a', 'b'].sort
['a', '2 b'].sort

# her kelimeden sonra birer boşluk var
['a ' , 'ab '].sort
```

**Comment by sbagdat** [comment]
@computalya Detaylı bildiriminiz için teşekkür ederim. Biraz geç olduğunun farkındayım ama ancak zaman bulabildim. Bu gibi durumlarda siz hatayı düzeltip, pull request gönderebilirseniz sevinirim.
